name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "JFLY SAYS $(git rev-parse HEAD)"
      - run: sleep 60
